repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: ''
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.6.4
  hooks:
  - id: isort
    args: ['--check-only', '--diff']