version: '3'
services:
    api:
        build: .
        command: uvicorn crawler_api.main:app --reload
        volumes:
            - ./:/opt/code
        container_name: api-legal-process
        networks:
            - default
