version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - ./crawler_api/:/opt/code
        container_name: api-legal-process
        networks:
            - default
